import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  resolve: {
    alias: {
      '@phozart/phz-shared/adapters': path.resolve(__dirname, 'packages/shared/src/adapters/index.ts'),
      '@phozart/phz-shared/types': path.resolve(__dirname, 'packages/shared/src/types/index.ts'),
      '@phozart/phz-shared/design-system': path.resolve(__dirname, 'packages/shared/src/design-system/index.ts'),
      '@phozart/phz-shared/artifacts': path.resolve(__dirname, 'packages/shared/src/artifacts/index.ts'),
      '@phozart/phz-shared/coordination': path.resolve(__dirname, 'packages/shared/src/coordination/index.ts'),
      '@phozart/phz-shared/definitions': path.resolve(__dirname, 'packages/shared/src/definitions/index.ts'),
      '@phozart/phz-shared': path.resolve(__dirname, 'packages/shared/src/index.ts'),
      '@phozart/phz-core': path.resolve(__dirname, 'packages/core/src/index.ts'),
      '@phozart/phz-engine/explorer': path.resolve(__dirname, 'packages/engine/src/explorer/index.ts'),
      '@phozart/phz-engine': path.resolve(__dirname, 'packages/engine/src/index.ts'),
      '@phozart/phz-criteria/shared-styles': path.resolve(__dirname, 'packages/criteria/src/shared-styles.ts'),
      '@phozart/phz-criteria': path.resolve(__dirname, 'packages/criteria/src/index.ts'),
      '@phozart/phz-grid': path.resolve(__dirname, 'packages/grid/src/index.ts'),
      '@phozart/phz-react': path.resolve(__dirname, 'packages/react/src/index.ts'),
      '@phozart/phz-vue': path.resolve(__dirname, 'packages/vue/src/index.ts'),
      '@phozart/phz-angular': path.resolve(__dirname, 'packages/angular/src/index.ts'),
      '@phozart/phz-duckdb': path.resolve(__dirname, 'packages/duckdb/src/index.ts'),
      '@phozart/phz-ai': path.resolve(__dirname, 'packages/ai/src/index.ts'),
      '@phozart/phz-collab': path.resolve(__dirname, 'packages/collab/src/index.ts'),
      '@phozart/phz-widgets': path.resolve(__dirname, 'packages/widgets/src/index.ts'),
      '@phozart/phz-definitions': path.resolve(__dirname, 'packages/shared/src/definitions/index.ts'),
      // Legacy shim names → workspace (archived packages, kept for test compatibility)
      '@phozart/phz-grid-admin': path.resolve(__dirname, 'packages/workspace/src/grid-admin/index.ts'),
      '@phozart/phz-engine-admin': path.resolve(__dirname, 'packages/workspace/src/engine-admin/index.ts'),
      '@phozart/phz-grid-creator': path.resolve(__dirname, 'packages/workspace/src/grid-creator/index.ts'),
      '@phozart/phz-workspace/grid-admin': path.resolve(__dirname, 'packages/workspace/src/grid-admin/index.ts'),
      '@phozart/phz-workspace/engine-admin': path.resolve(__dirname, 'packages/workspace/src/engine-admin/index.ts'),
      '@phozart/phz-workspace/grid-creator': path.resolve(__dirname, 'packages/workspace/src/grid-creator/index.ts'),
      '@phozart/phz-workspace/criteria-admin': path.resolve(__dirname, 'packages/workspace/src/criteria-admin/index.ts'),
      '@phozart/phz-workspace/definition-ui': path.resolve(__dirname, 'packages/workspace/src/definition-ui/index.ts'),
      '@phozart/phz-workspace/client': path.resolve(__dirname, 'packages/workspace/src/client/index.ts'),
      '@phozart/phz-workspace/registry': path.resolve(__dirname, 'packages/workspace/src/registry/index.ts'),
      '@phozart/phz-workspace/schema': path.resolve(__dirname, 'packages/workspace/src/schema/index.ts'),
      '@phozart/phz-workspace/alerts': path.resolve(__dirname, 'packages/workspace/src/alerts/index.ts'),
      '@phozart/phz-workspace/filters': path.resolve(__dirname, 'packages/workspace/src/filters/index.ts'),
      '@phozart/phz-workspace/explore': path.resolve(__dirname, 'packages/workspace/src/explore/index.ts'),
      '@phozart/phz-workspace/templates': path.resolve(__dirname, 'packages/workspace/src/templates/index.ts'),
      '@phozart/phz-workspace/layout': path.resolve(__dirname, 'packages/workspace/src/layout/index.ts'),
      '@phozart/phz-workspace/connectors': path.resolve(__dirname, 'packages/workspace/src/adapters/remote-connector.ts'),
      '@phozart/phz-workspace': path.resolve(__dirname, 'packages/workspace/src/index.ts'),
      '@phozart/phz-local': path.resolve(__dirname, 'packages/local/src/index.ts'),
      '@phozart/phz-viewer/react': path.resolve(__dirname, 'packages/viewer/src/react/index.ts'),
      '@phozart/phz-viewer': path.resolve(__dirname, 'packages/viewer/src/index.ts'),
      '@phozart/phz-editor/react': path.resolve(__dirname, 'packages/editor/src/react/index.ts'),
      '@phozart/phz-editor': path.resolve(__dirname, 'packages/editor/src/index.ts'),
    },
  },
  test: {
    globals: true,
    environment: 'node',
    include: ['packages/*/src/**/*.test.ts', 'tests/**/*.test.ts'],
    coverage: {
      provider: 'istanbul',
      include: ['packages/*/src/**/*.ts'],
      exclude: ['**/*.test.ts', '**/*.d.ts', '**/index.ts'],
      reporter: ['text', 'json', 'lcov'],
      thresholds: {
        statements: 55,
        branches: 70,
        functions: 50,
        lines: 55,
      },
    },
  },
});
